src/main/java/com/nhnacademy/illuwa/memberaddress/client/MemberAddressServiceClient.java
- /api/ 붙이고 임시 테스트
- Closed: #
=> test: tmp /api/ test

src/main/java/com/nhnacademy/illuwa/book/controller/BookListController.java, src/main/java/com/nhnacademy/illuwa/cart/client/CartServiceClient.java, src/main/java/com/nhnacademy/illuwa/cart/controller/CartController.java, src/main/java/com/nhnacademy/illuwa/cart/dto/CartResponse.java, src/main/java/com/nhnacademy/illuwa/cart/service/CartService.java, src/main/resources/static/js/book/booklist.js, src/main/resources/static/js/cart/cart.js, src/main/resources/templates/book/book_list.html, src/main/resources/templates/user/cart.html
=> feat: 장바구니 담기

src/main/java/com/nhnacademy/illuwa/coupon/client/CouponServiceClient.java, src/main/java/com/nhnacademy/illuwa/coupon/controller/MyCouponController.java, src/main/java/com/nhnacademy/illuwa/coupon/dto/MemberCouponResponse.java, src/main/java/com/nhnacademy/illuwa/coupon/service/MemberCouponService.java
=> [FEAT] : 사용자 쿠폰발급,사용내역조회

src/main/java/com/nhnacademy/illuwa/cart/client/CartServiceClient.java, src/main/java/com/nhnacademy/illuwa/cart/controller/CartController.java, src/main/java/com/nhnacademy/illuwa/cart/service/CartService.java, src/main/resources/static/js/book/booklist.js, src/main/resources/static/js/cart/cart.js, src/main/resources/templates/book/book_list.html, src/main/resources/templates/book/detail.html, src/main/resources/templates/user/cart.html
>  개별 삭제, 도서 상세페이지에서 장바구니 담기
- Closed: #178
=> feat: 개별삭제, 도서 상세페이지 장바구니 담기

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java, src/main/java/com/nhnacademy/illuwa/admin/controller/AdminCategoryController.java, src/main/java/com/nhnacademy/illuwa/admin/controller/AdminTagController.java, src/main/java/com/nhnacademy/illuwa/book/dto/BookDetailWithExtraInfoResponse.java, src/main/java/com/nhnacademy/illuwa/tag/client/TagServiceClient.java, src/main/java/com/nhnacademy/illuwa/tag/dto/PageResponse.java, src/main/java/com/nhnacademy/illuwa/tag/dto/TagCreateRequest.java, src/main/java/com/nhnacademy/illuwa/tag/dto/TagResponse.java, src/main/resources/templates/admin/book/books.html, src/main/resources/templates/admin/book/manage.html, src/main/resources/templates/admin/tag/manage.html
- 카테고리 페이지네이션 기능을 위한 **Pagination DTO** 추가
- 도서 상세 정보 DTO에 **태그 정보 반영**
- **관리자 태그 API** 추가 (생성/삭제/조회)
- Feign Client에 태그 API 연동
- 관리자 태그 관리 페이지 UI/테이블 컬럼에 태그 표시
- 카테고리 및 태그 관리 관련 Controller 경로 이동 및 주석 정리
- .
- Closed: #208
=> [FEAT] 도서 태그

src/main/java/com/nhnacademy/illuwa/coupon/dto/MemberCouponResponse.java, src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java, src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java, src/main/java/com/nhnacademy/illuwa/order/dto/BookItemOrderDto.java, src/main/java/com/nhnacademy/illuwa/order/dto/OrderCreateResponse.java, src/main/java/com/nhnacademy/illuwa/order/dto/OrderItemResponseDto.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberAddressDto.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderDirectRequest.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderInitDirectResponse.java, src/main/java/com/nhnacademy/illuwa/order/dto/orderRequest/OrderItemDto.java, src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java, src/main/resources/static/js/order/order_member_form.js, src/main/resources/templates/book/detail.html, src/main/resources/templates/order/order_member_form.html, src/main/resources/templates/order/order_view.html
- 회원 주문하기 코드 추가, html 코드추가
이거 html css 리팩토링 같은거 한번에 시키겠습니다. 그리고 정환님 쿠폰쪽 사용기한 같은거 타입이 LocalDateTime이 아니라 LocalDate으로 참고부탁드립니다.
- Closed: #166
=> Feat: #166 회원 바로 주문하기 추가

src/main/resources/static/js/address/address.js, src/main/resources/templates/memberaddress/address_list.html
=> fix: 주소 버그 수정

src/main/resources/static/js/auth/inactive-verification.js
- 혹시몰라서 기본값 제거하고 apiBaseUrl이 잘 작동하도록 테스트
- Closed: #
=> fix: baseUrl localhost 기본값 제거

src/main/resources/application.yml
=> 7/14 master 업데이트

src/main/resources/static/js/auth/inactive-verification.js
=> feat: baseUrl 설정 (임시)

src/main/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClient.java, src/main/java/com/nhnacademy/illuwa/auth/controller/InactiveVerificationProxy.java, src/main/java/com/nhnacademy/illuwa/auth/controller/LoginController.java, src/main/java/com/nhnacademy/illuwa/auth/dto/SendMessageResponse.java, src/main/java/com/nhnacademy/illuwa/auth/dto/VerifyCodeRequest.java, src/main/java/com/nhnacademy/illuwa/auth/dto/VerifyCodeResponse.java, src/main/java/com/nhnacademy/illuwa/config/SecurityConfig.java, src/main/resources/static/js/auth/inactive-verification.js
=> feat: ProxyController 구조로 변경

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java, src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java, src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderCartRequest.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderInitFromCartResponse.java, src/main/java/com/nhnacademy/illuwa/order/dto/orderRequest/OrderItemDto.java, src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java, src/main/resources/static/js/order/order_member_cart_form.js, src/main/resources/templates/order/order_cart_view.html, src/main/resources/templates/order/order_member_cart_form.html, src/main/resources/templates/order/order_member_form.html, src/main/resources/templates/user/cart.html
- 장바구니 주문하기 구현
@Valid는 나머지 로직 완료하고 구현하겠습니다.
- Closed: #231
=> Feat: #231 장바구니 주문하기 구현

src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java, src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberCouponDto.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderInitDirectResponse.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderInitFromCartResponse.java, src/main/java/com/nhnacademy/illuwa/order/dto/orderRequest/MemberOrderInfo.java, src/main/resources/static/js/order/order_member_cart_form.js, src/main/resources/templates/order/order_cart_view.html, src/main/resources/templates/order/order_member_cart_form.html, src/main/resources/templates/order/order_member_form.html, src/main/resources/templates/order/order_view.html
- 회원 장바구니 주문하기 구현
- Closed: #231
=> Feat: #231 회원 장바구니 주문하기 구현

src/main/java/com/nhnacademy/illuwa/config/AuthInterceptor.java
- url param 노출 문제 해결
- Closed: #246
=> refactor: url param 노출 문제 해결

src/main/resources/templates/error.html, src/test/java/com/nhnacademy/illuwa/auth/client/AuthClientTest.java, src/test/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClientTest.java, src/test/java/com/nhnacademy/illuwa/auth/client/PaycoUserInfoClientTest.java, src/test/java/com/nhnacademy/illuwa/auth/controller/LoginControllerTest.java, src/test/java/com/nhnacademy/illuwa/auth/service/InactiveVerificationServiceTest.java
- error.html 수정
- Closed: #252
=> refactor: error.html 수정

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminCouponController.java, src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java, src/main/java/com/nhnacademy/illuwa/book/service/BookService.java, src/main/resources/static/js/coupon/coupon.js, src/main/resources/templates/admin/coupon/coupon_create.html
- 이전 도서ID를 모달을 통해 주입했던것과 같이 카테고리ID도 모달을 통해 주입
- Closed: #255
=> [REFACTOR] 관리자 쿠폰 생성 로직 수정

src/main/resources/templates/home.html
- home.html 수정 - 비회원 로그인 삭제
- Closed: #266
=> refactor: #266 메인 페이지 비회원 로그인 삭제

src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java, src/main/java/com/nhnacademy/illuwa/member/client/MemberServiceClient.java, src/main/java/com/nhnacademy/illuwa/member/service/MemberService.java, src/main/resources/templates/book/detail.html
- Map<Long, String> feign 메서드 추가
- Closed: #272
=> [FEAT] 리뷰작성자 이름으로 가져오게 변경

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java
=> fix(search): 도서이미지 mixed content 해결

src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java, src/main/java/com/nhnacademy/illuwa/member/client/MemberServiceClient.java
=> [FIX] 필요없는 import 삭제, 경로매핑 / 빠져서 추가

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java, src/main/resources/templates/admin/order/order_detail.html, src/main/resources/templates/book/detail.html, src/main/resources/templates/order/order_cart_view.html, src/main/resources/templates/order/order_detail.html, src/main/resources/templates/order/order_guest_form.html, src/main/resources/templates/order/order_member_form.html
=> refactor: html 수정

src/main/java/com/nhnacademy/illuwa/book/service/BookService.java, src/main/java/com/nhnacademy/illuwa/search/client/BookSearchClient.java, src/main/java/com/nhnacademy/illuwa/search/controller/BookSearchController.java, src/main/resources/templates/book/search_result.html, src/main/resources/templates/layout/header.html, src/main/resources/templates/layout/layout.html
• BookSearchClient의 Feign 경로 수정
• BookSearchController의 검색 API 경로 수정
• 사용하지 않는 API 주석 처리
• header.html 내 검색 요청 경로 수정
• 검색 결과 페이지의 경로 및 라우팅 수정
- Closed: #
=> [FIX] 도서 검색 endpoint path 수정

src/main/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClient.java
=> fix: login api 경로 수정

src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java, src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java, src/main/java/com/nhnacademy/illuwa/order/controller/OrderDetailController.java, src/main/java/com/nhnacademy/illuwa/payment/client/PaymentServiceClient.java, src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java, src/main/java/com/nhnacademy/illuwa/payment/dto/PaymentRefundRequest.java, src/main/resources/templates/order/order_detail.html
- 환불 관련 로직 구현입니다.
- review와 관련된 부분 들에서, 에러가 발생하여 임의로 주석처리 후 로직 구현 하였습니다.
- Conflict 많이 발생할 가능성 있다면, 해당 PR merge 전 주석 해제 후 push 한번 더 하겠습니다.
- Closed: #
=> feat: 환불 로직 구현

src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java
- 장바구니 물품 결제 후, 장바구니 비우기 로직을 추가 하였습니다.
- Closed: #
=> feat: 장바구니 주문 후 장바구니 비우기 구현

src/test/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClientTest.java
=> fix: API 주소 변경으로 인한 테스트 코드 매핑 주소 변경

src/main/java/com/nhnacademy/illuwa/auth/controller/ExtraInfoController.java, src/main/java/com/nhnacademy/illuwa/auth/controller/InactiveVerificationController.java, src/main/java/com/nhnacademy/illuwa/auth/controller/LoginController.java, src/main/java/com/nhnacademy/illuwa/auth/controller/SignupController.java, src/main/java/com/nhnacademy/illuwa/auth/oauth/OAuth2LoginSuccessHandler.java, src/main/java/com/nhnacademy/illuwa/config/SecurityConfig.java, src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java, src/main/resources/static/js/auth/inactive-verification.js
- RESTful 설계를 위한 URI 리팩토링 작업완료했습니다.
- 다른 도메인도 URI 먼저 수정해두고, API 도 구조 변경 진행하려 합니다.
- Closed: #
=> refactor: auth-service Front URI 수정

src/main/resources/templates/auth/extra-info.html, src/main/resources/templates/auth/login.html, src/main/resources/templates/auth/signup.html
=> refactor: login html 수정

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java, src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java, src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java, src/main/java/com/nhnacademy/illuwa/order/controller/OrderDetailController.java, src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java, src/main/resources/static/js/order/order_guest_form.js, src/main/resources/static/js/order/order_member_cart_form.js, src/main/resources/static/js/order/order_member_form.js, src/main/resources/templates/admin/member/member_list.html, src/main/resources/templates/order/order_detail.html, src/main/resources/templates/order/order_guest_form.html, src/main/resources/templates/order/order_member_form.html
=> Feat: #322 member grade

src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java, src/main/resources/templates/layout/header.html
- feat: 비로그인 헤더 장바구니 숨기기
- 
- Closed: #319
=> feat: 비로그인 헤더 장바구니 숨기기

src/main/resources/templates/home.html, src/main/resources/templates/layout/header.html
=> bugfix: html 링크 버그

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java, src/main/java/com/nhnacademy/illuwa/admin/controller/AdminTagController.java, src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java, src/main/java/com/nhnacademy/illuwa/book/dto/BookDetailWithExtraInfoResponse.java, src/main/java/com/nhnacademy/illuwa/tag/client/TagServiceClient.java, src/main/resources/templates/admin/book/manage.html, src/main/resources/templates/layout/layout.html
- 관리페이지에서 직접 태그 등록 / 삭제를 할 수 있는 API 추가
- . 
- 
- Closed: #310
=> [FEAT] 도서 태그 관리 API 연동

src/main/java/com/nhnacademy/illuwa/order/client/OrderServiceClient.java, src/main/java/com/nhnacademy/illuwa/order/controller/MemberOrderController.java, src/main/java/com/nhnacademy/illuwa/order/dto/GuestLoginRequest.java, src/main/java/com/nhnacademy/illuwa/order/dto/OrderListResponse.java, src/main/java/com/nhnacademy/illuwa/order/dto/admin/OrderUpdateStatusDto.java, src/main/java/com/nhnacademy/illuwa/order/dto/guest/GuestOrderDirectRequest.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderCartRequest.java, src/main/java/com/nhnacademy/illuwa/order/dto/member/MemberOrderDirectRequest.java, src/main/java/com/nhnacademy/illuwa/order/dto/orderRequest/MemberOrderInfo.java, src/main/java/com/nhnacademy/illuwa/order/dto/orderRequest/OrderItemDto.java, src/main/java/com/nhnacademy/illuwa/order/dto/types/ReturnReason.java, src/main/java/com/nhnacademy/illuwa/order/service/OrderService.java, src/main/java/com/nhnacademy/illuwa/order/service/OrderStatusMemberService.java, src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java, src/main/resources/static/css/order/mypage_order_list.css, src/main/resources/static/css/order/order_detail.css, src/main/resources/templates/admin/order/order_detail.html, src/main/resources/templates/order/order_detail.html, src/main/resources/templates/order/order_list.html
=> Feat/335 dto 검증 추가

src/main/java/com/nhnacademy/illuwa/pointhistory/enums/PointHistoryType.java, src/main/java/com/nhnacademy/illuwa/pointhistory/enums/PointReason.java, src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java, src/main/java/com/nhnacademy/illuwa/review/controller/ReviewController.java, src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java, src/main/resources/templates/layout/mypage-sidebar.html, src/main/resources/templates/mypage/section/point_history.html, src/main/resources/templates/mypage/section/review_history.html, src/main/resources/templates/review/review_form.html, src/test/java/com/nhnacademy/illuwa/member/service/AdminMemberServiceTest.java
- PointReason enum 타입 수정건 반영 (테스트코드도 수정)
- 내가 쓴 리뷰 페이지 구현
: 책 제목 / 리뷰제목/ 평점
- 리뷰 상세 : 주문목록으로 가기 버튼 -> 이전 페이지로 돌아가기 버튼으로 수정(내가 쓴 리뷰 또는 주문상세로 돌아갈 수 있게끔)
- Closed: #338
=> Feat: #338 내가 쓴 리뷰 페이지

src/main/java/com/nhnacademy/illuwa/booklike/client/BookLikeServiceClient.java, src/main/java/com/nhnacademy/illuwa/booklike/controller/BookLikeController.java, src/main/resources/static/css/page/book/detail.css, src/main/resources/static/css/page/member/book-likes.css, src/main/resources/static/css/page/review/_review_form.css, src/main/resources/templates/book/detail.html, src/main/resources/templates/mypage/section/book_likes.html, src/main/resources/templates/review/review_form.html
- RequestParam 이름 지정 (수정사항이 누락되었던 것으로 보임..)
- 좋아요한 도서 목록에서 도서 누르면 도서 상세로 이동 구현
- Closed: #350
=> bugfix: #350 도서 좋아요 버그 해결

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java, src/main/java/com/nhnacademy/illuwa/admin/controller/AdminHomeController.java, src/main/java/com/nhnacademy/illuwa/admin/controller/AdminTagController.java, src/main/resources/templates/admin/admin_home.html, src/main/resources/templates/admin/book/book_register.html, src/main/resources/templates/admin/book/book_register_api.html, src/main/resources/templates/admin/book/book_search_results.html, src/main/resources/templates/admin/book/book_update.html, src/main/resources/templates/admin/book/books.html, src/main/resources/templates/admin/book/manage.html, src/main/resources/templates/admin/tag/manage.html, src/main/resources/templates/home.html
- 도서 관리 부분 URI 수정 사항입니다.
- Closed: #
=> refactor: admin BookController URI 수정

src/main/java/com/nhnacademy/illuwa/booklike/client/BookLikeServiceClient.java, src/main/java/com/nhnacademy/illuwa/booklike/controller/BookLikeController.java, src/main/java/com/nhnacademy/illuwa/booklike/service/BookLikeService.java, src/main/resources/static/css/page/book/detail.css, src/main/resources/templates/book/detail.html
- BookLikeController, BookLikeClient uri 수정
- 수량/ 장바구니/ 주문하기 /책 좋아요 버튼 일렬정렬
- 좋아요(리뷰, 도서) 버튼 공통 디자인 적용
- Closed: #354
=> feat: #354 BookLikeController uri 변경 및 css 추가

src/main/java/com/nhnacademy/illuwa/auth/utils/JwtCookieUtil.java
=> refactor: jwt 쿠키 로직 수정

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java, src/main/java/com/nhnacademy/illuwa/order/client/CommonOrderClient.java, src/main/java/com/nhnacademy/illuwa/order/client/GuestOrderClient.java, src/main/java/com/nhnacademy/illuwa/order/controller/member/command/MemberOrderStatusController.java, src/main/java/com/nhnacademy/illuwa/order/dto/command/create/GuestOrderDirectRequest.java, src/main/java/com/nhnacademy/illuwa/order/dto/command/status/ReturnRequestCreateRequest.java, src/main/java/com/nhnacademy/illuwa/order/service/CommonOrderService.java, src/main/java/com/nhnacademy/illuwa/order/service/impl/CommonOrderServiceImpl.java, src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java
=> refactor: #364 자잘한 코드 수정

src/main/resources/templates/book/book_list.html, src/test/java/com/nhnacademy/illuwa/cart/controller/CartControllerTest.java
=> fix: 도서 목록 조회 수정, 테스트 코드 추가

src/main/resources/templates/admin/book/book_register.html, src/main/resources/templates/admin/book/book_register_api.html
> 도서 등록 form에서 설명에 ToastUI 적용
- Closed: #359
=> [FEAT] 도서 등록 form 개선 - toastUI 적용

.github/workflows/sonarqube.yml, pom.xml
- SonarQube 자동화 workflow 추가했습니다.
- Closed: #
=> feat: sonarqube 의존성 및 workflow 추가

src/main/resources/static/css/component/_button.css, src/main/resources/static/css/page/_home.css, src/main/resources/templates/book/book_list.html, src/main/resources/templates/book/search_result.html, src/main/resources/templates/home.html, src/main/resources/templates/layout/layout.html
- refactor: html 세부 변경
- Closed: #371
=> refactor: html 세부 변경

src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java
=> fix: review like API 수정

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java
=> fix: Order Controller uri 수정

src/main/java/com/nhnacademy/illuwa/book/controller/BookController.java, src/main/java/com/nhnacademy/illuwa/book/controller/BookInfoController.java, src/main/java/com/nhnacademy/illuwa/book/controller/BookListController.java, src/main/resources/templates/book/book_list.html, src/main/resources/templates/home.html, src/main/resources/templates/layout/header.html
- 도서 관련 URI 수정 입니다.
- Closed: #
=> refactor: Book 관련 URI 수정

src/test/java/com/nhnacademy/illuwa/coupon/controller/CouponControllerTest.java, src/test/java/com/nhnacademy/illuwa/coupon/controller/MyCouponControllerTest.java
- 사용자 쿠폰 발급 컨트롤러 테스트 코드 작성,
- 사용자 쿠폰함 조회 컨트롤러 테스트 코드 작성 
- 카테고리 임포트 위치 변경
- Closed: #405
=> [REFACTOR] 사용자 쿠폰 발급 및 조회 컨트롤러 테스트 코드 작성

src/main/resources/templates/admin/book/book_update.html
- 체크박스를 체크해도 변경사항이 반영되지 않는 문제해결
- update.html 수정 
- DB 반영 확인( check -> 1 / unchecked ->0 ) Boolean
- Closed: #
=> [FIX] 도서 수정 - 포장 여부 반영 Issue 해결

src/main/java/com/nhnacademy/illuwa/review/client/ReviewServiceClient.java, src/main/resources/static/css/page/book/detail.css, src/main/resources/static/css/page/review/_review_form.css, src/main/resources/templates/book/detail.html, src/main/resources/templates/review/review_form.html
- 리뷰이미지 위치, 사이즈 조정
- RequestParam reviewIds-> review-ids 변경 
- Closed: #417
=> [FEAT] 리뷰 이미지 위치 조정

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminOrderController.java, src/main/java/com/nhnacademy/illuwa/order/dto/types/OrderStatus.java, src/main/java/com/nhnacademy/illuwa/order/dto/types/ReturnReason.java, src/main/resources/templates/admin/order/order_detail.html, src/main/resources/templates/order/order_detail.html
- html 잘못된 포스트 경로 수정
- Closed: #422
=> bug fix: post 주소 변경

src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java, src/main/java/com/nhnacademy/illuwa/book/dto/BookApiRegisterRequest.java, src/main/resources/templates/admin/book/book_register.html, src/main/resources/templates/book/detail.html, src/test/java/com/nhnacademy/illuwa/book/client/ProductClientTest.java
- product-service 측의 개선사항을 반영해서 api 경로 수정
- 도서 설명 db에 저장이 안되는 issue 해결
- 도서 태그가 그대로 출력되지 않고, ui 반영되서 출력되도록 수정
- Closed: #
=> [REFACTOR] endpoint 경로 수정

src/main/java/com/nhnacademy/illuwa/coupon/dto/coupon/CouponResponse.java, src/main/java/com/nhnacademy/illuwa/coupon/dto/couponPolicy/CouponPolicyResponse.java, src/main/resources/templates/admin/coupon/coupon_view_list.html, src/main/resources/templates/admin/policy/coupon_policy_view_list.html, src/main/resources/templates/user/couponpage.html
- BigDecimal 타입 클라이언트 입장에서의 소숫점 자리 제외,
- html -> th문법 엔드포인트 이동경로 (update -> form)으로 수정
- Closed: #427
=> [REFACTOR] BigDecimal 타입 소숫점 자리 제외

src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java, src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java, src/main/resources/static/css/page/review/_review_form.css, src/main/resources/templates/mypage/section/review_history.html, src/main/resources/templates/review/review_form.html
=> [FEAT] 이미지 깨짐 오류 수정 

src/main/java/com/nhnacademy/illuwa/config/AuthInterceptor.java
- 기존 Interceptor 에서 쿠키를 중복 파싱 하는 부분을 제거하였습니다.
- Closed: #
=> refactor: Interceptor 쿠키 파싱 부분 제거

src/main/resources/templates/order/order_detail.html
=> feat: 결제 취소 구현

src/main/resources/templates/order/order_detail.html
=> feat: 결제 취소 구현완료

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java, src/main/java/com/nhnacademy/illuwa/admin/controller/AdminCouponController.java, src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java, src/main/java/com/nhnacademy/illuwa/book/runner/PreCacheRunner.java, src/main/java/com/nhnacademy/illuwa/book/service/BookService.java, src/main/java/com/nhnacademy/illuwa/category/client/CategoryServiceClient.java, src/main/java/com/nhnacademy/illuwa/config/AuthInterceptor.java, src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java, src/main/resources/static/css/page/review/_review_form.css, src/main/resources/templates/mypage/section/review_history.html, src/main/resources/templates/order/order_detail.html, src/main/resources/templates/review/review_form.html, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminBookControllerTest.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminCategoryControllerTest.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminCouponControllerTest.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminCouponPolicyControllerTest.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminHomeControllerTest.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminMemberControllerTest.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminOrderControllerTest.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminPackagingControllerTest.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminTagControllerTest.java, src/test/java/com/nhnacademy/illuwa/auth/client/AuthClientTest.java, src/test/java/com/nhnacademy/illuwa/auth/client/InactiveVerificationServiceClientTest.java, src/test/java/com/nhnacademy/illuwa/book/client/ProductClientTest.java, src/test/java/com/nhnacademy/illuwa/book/service/BookServiceTest.java, src/test/java/com/nhnacademy/illuwa/member/client/AdminMemberServiceClientTest.java
- 인기도서를 불러올 때 applicatoin 시작과 동시에 캐시에 바로 저장
- . bestseller 도서 목록을 불러오는 과정 개선
- Closed: #430
=> [REFACTOR] ApplicationRunner를 구현한 preCahceRunner를 컴포넌트 등록

src/main/java/com/nhnacademy/illuwa/order/client/AdminOrderClient.java, src/main/java/com/nhnacademy/illuwa/order/client/CommonOrderClient.java, src/main/java/com/nhnacademy/illuwa/order/client/GuestOrderClient.java, src/main/java/com/nhnacademy/illuwa/order/client/MemberOrderClient.java, src/main/java/com/nhnacademy/illuwa/order/client/PackagingClient.java
- 주문 Client 주소 변경에 따른 Client API 경로 수정
- Closed: #426
=> refactor: API 주소 변경

src/main/java/com/nhnacademy/illuwa/review/service/ReviewService.java, src/main/resources/templates/review/review_form.html
-  리뷰상세 페이지 반영안된 문제점 수정 
- Closed: #431
=> fix: 서버 이미지 깨지는 오류 2차 

src/main/java/com/nhnacademy/illuwa/admin/controller/AdminBookController.java, src/main/java/com/nhnacademy/illuwa/book/client/ProductServiceClient.java, src/main/java/com/nhnacademy/illuwa/book/runner/PreCacheRunner.java, src/main/java/com/nhnacademy/illuwa/category/controller/CategoryController.java, src/test/java/com/nhnacademy/illuwa/admin/controller/AdminBookControllerTest.java, src/test/java/com/nhnacademy/illuwa/book/client/ProductClientTest.java
- 테스트 코드 재수정
- dategory 목록 불러오는 api path 수정
- Closed: #
=> [FIX] category endpoint 수정(2)

src/main/java/com/nhnacademy/illuwa/search/client/BookSearchClient.java
- 도서 검색 api endpoint 동기화
- Closed: #
=> [REFACTOR] 도서 검색 api endpoint 경로 수정

src/main/java/com/nhnacademy/illuwa/book/service/BookService.java, src/main/resources/templates/admin/tag/manage.html
> 공통된 pagination DTO 통합 후 manage.html에 반영 안된 issue
- 
- Closed: #
=> [BUG] 태그 관리 페이지  

src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java, src/main/java/com/nhnacademy/illuwa/payment/dto/PaymentConfirmRequest.java, src/main/resources/templates/order/order_view.html
=> feat: 결제 멱등성 키 생성

src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java, src/main/java/com/nhnacademy/illuwa/payment/dto/PaymentConfirmRequest.java, src/main/resources/templates/order/order_view.html
=> fix: PaymentRequest 원상복구

src/main/java/com/nhnacademy/illuwa/payment/controller/PaymentController.java
=> feat: 결제 프로세스 시간 측정 테스트 - 동기 처리
